# Company cards for the answer queue. Five fields per ticker:
#   where — casual rung 3: store | home | hidden (see WHERE_CLUE in template.html)
#   emoji — 3-emoji visual clue
#   what  — reveal card: plain-English "what they actually do" (no numbers, no jargon)
#   hint  — casual rung 5 "you might know them from" (spoiler-free: never names the company)
#   fact  — degen rung 2 / casual rung 4. RULE: it must CONSTRAIN, not identify. "Founded in a
#           Denny's" is a bad clue — you either know it and it's the answer, or you don't and it's
#           nothing. Write properties a knowledgeable player can filter on. Optional; falls back.
CO = {
 "MU":    {"where":"hidden", "emoji":"💾🧠📱", "what":"Micron makes memory chips — the storage and RAM inside phones, laptops and the data centers that run AI.", "hint":"the memory chips inside your phone and AI data centers", "fact":'Only three companies in the world still make this commodity chip at scale, and the price swings violently with supply.'},
 "GME":   {"where":"store", "emoji":"🎮🕹️🚀", "what":"GameStop is the mall video-game retailer that became the most famous meme stock on earth in 2021.", "hint":"the mall video-game store that broke Wall Street in 2021", "fact":'A 2021 squeeze let it sell new shares into the frenzy and wipe out its debt — the mania funded the balance sheet.'},
 "CRCL":  {"where":"hidden", "emoji":"💵🔵🪙", "what":"Circle issues USDC — a 'digital dollar' stablecoin used to move money around the crypto world.", "hint":"the company behind the USDC digital dollar", "fact":"Almost all of its money comes from the interest it earns on other people's dollars."},
 "CAT":   {"where":"hidden", "emoji":"🚜🏗️🟡", "what":"Caterpillar builds the yellow bulldozers, excavators and mining trucks you see on every construction site.", "hint":"the yellow bulldozers on every construction site", "fact":'Its dealers are independent businesses, and its financing arm is a bank in all but name.'},
 "MSTR":  {"where":"hidden", "emoji":"₿💻🏦", "what":"Strategy (born MicroStrategy) is a software company that turned itself into a giant leveraged Bitcoin vault.", "hint":"the software company that turned itself into a Bitcoin vault", "fact":"For twenty years it sold business software. Then it decided its real product was its balance sheet."},
 "AAPL":  {"where":"store", "emoji":"📱💻⌚", "what":"Apple makes the iPhone, Mac and Apple Watch — and takes a cut of everything in the App Store.", "hint":"the phone that's probably in your hand right now", "fact":'A single product line still drives most of the revenue, with a fast-growing slice coming from services sold to people who already own the hardware.'},
 "SNDK":  {"where":"home", "emoji":"💾📷🔌", "what":"SanDisk makes flash memory — the storage in memory cards, USB drives and SSDs.", "hint":"the memory cards in your camera and the USB stick in your drawer", "fact":"A hard-drive maker bought it in 2016, then spun it back out on its own last year."},
 "NKE":   {"where":"store", "emoji":"👟✅🏅", "what":"Nike is the world's biggest sneaker and sportswear brand — the swoosh, Air Jordans, 'Just Do It.'", "hint":"the swoosh on half the sneakers you own", "fact":'It owns virtually no factories; contractors across Asia make everything it sells.'},
 "PLTR":  {"where":"hidden", "emoji":"🕵️📊🔮", "what":"Palantir sells secretive data-analysis software used by governments, militaries and big companies.", "hint":"the secretive data software used by governments and militaries", "fact":"It's named after a magic seeing-stone from a fantasy novel."},
 "INTC":  {"where":"hidden", "emoji":"💻🔵⚙️", "what":"Intel is the classic PC chip maker — the processor 'inside' decades of computers, now fighting its way back.", "hint":"the classic 'inside your PC' chip maker", "fact":'It both designs and manufactures its own chips — almost none of its competitors still do both.'},
 "DIS":   {"where":"store", "emoji":"🏰🐭🎬", "what":"Disney owns Mickey Mouse, Marvel, Star Wars, Pixar, ESPN and the theme parks.", "hint":"Mickey Mouse, Marvel and the theme parks", "fact":'Its theme parks routinely out-earn its film studio.'},
 "COIN":  {"where":"home", "emoji":"🪙📱₿", "what":"Coinbase is the biggest US crypto exchange — the app most Americans use to buy Bitcoin.", "hint":"the app most Americans use to buy Bitcoin", "fact":'Its revenue tracks trading volume, so its results swing with the price of a single asset class.'},
 "MSFT":  {"where":"home", "emoji":"🪟📊🎮", "what":"Microsoft makes Windows, Office, Xbox and the Azure cloud — and is a major backer of OpenAI.", "hint":"Windows, Office and Xbox", "fact":'Its cloud division has been growing faster than the desktop software everyone associates it with.'},
 "AMD":   {"where":"hidden", "emoji":"🎮🖥️🔴", "what":"AMD designs the chips inside gaming PCs, consoles and servers — Nvidia's arch-rival in AI chips.", "hint":"gaming PC chips — the arch-rival of the AI chip king", "fact":'It sold off its factories in 2009 and has depended on outside Asian foundries to build its chips ever since.'},
 "NFLX":  {"where":"home", "emoji":"🍿📺🔴", "what":"Netflix is the world's biggest streaming service — the one that invented binge-watching.", "hint":"the streaming app you fall asleep to", "fact":"It spends more making its own shows than licensing anyone else's — a deliberate reversal of how it started."},
 "HOOD":  {"where":"home", "emoji":"🪶📈📱", "what":"Robinhood is the commission-free trading app that brought a generation of first-timers into the stock market.", "hint":"the free stock-trading app with the feather logo", "fact":'A large chunk of its revenue comes from routing customer orders to bigger trading firms rather than from the customers themselves.'},
 "LULU":  {"where":"store", "emoji":"🧘👖🛍️", "what":"Lululemon sells premium yoga pants and athleisure — the brand that made leggings a status symbol.", "hint":"the yoga pants", "fact":'It sells at full price far more often than most apparel brands and rarely runs discounts.'},
 "DELL":  {"where":"home", "emoji":"💻🖥️⌨️", "what":"Dell builds PCs, laptops and the servers that data centers — including AI ones — run on.", "hint":"the computer brand from the old 'Dude, you're getting a…' ads", "fact":'It left the public market in 2013 and came back to it five years later.'},
 "BA":    {"where":"hidden", "emoji":"✈️🛫🔧", "what":"Boeing builds the 737 and 787 — half the planes you've ever flown on.", "hint":"maker of half the planes you've flown on", "fact":'It operates in a duopoly — exactly one other company on earth builds what it builds.'},
 "TSLA":  {"where":"store", "emoji":"🚗⚡🔋", "what":"Tesla makes electric cars, the Cybertruck, home batteries — and bets big on robots and self-driving.", "hint":"the electric car with the most famous CEO on earth", "fact":'It sells straight to the customer instead of through franchised dealers, which is illegal in several US states.'},
 "GEMI":  {"where":"home", "emoji":"♊🪙👯", "what":"Gemini is the crypto exchange founded by the Winklevoss twins of Facebook-lawsuit fame.", "hint":"the Winklevoss twins' crypto exchange", "fact":"The stock exchange it trades on invested in it just before the listing."},
 "SBUX":  {"where":"store", "emoji":"☕🟢🧜‍♀️", "what":"Starbucks is the world's biggest coffee chain — the green mermaid on every corner.", "hint":"the green mermaid on your coffee cup", "fact":'China is its second-largest market and by far its most contested one.'},
 "MRVL":  {"where":"hidden", "emoji":"📡🔌💾", "what":"Marvell designs the networking chips that move data around clouds and AI data centers.", "hint":"chips that shuttle data around AI data centers", "fact":'It designs chips, owns no factories, and sells almost nothing directly to consumers.'},
 "IBM":   {"where":"hidden", "emoji":"🖥️🔵💼", "what":"IBM — 'Big Blue' — is the original computer giant, now selling cloud, consulting and mainframes.", "hint":"'Big Blue' — the original computer giant", "fact":'It is more than a century old and now earns most of its money from software and consulting rather than machines.'},
 "RIVN":  {"where":"store", "emoji":"🛻⚡📦", "what":"Rivian makes electric pickups and SUVs — and the vans that deliver your Amazon packages.", "hint":"the electric vans that deliver your Amazon packages", "fact":'One of its largest shareholders is also one of its largest customers.'},
 "KO":    {"where":"home", "emoji":"🥤🔴🐻", "what":"Coca-Cola sells the world's most famous drink — plus Sprite, Fanta, Smartwater and hundreds more.", "hint":"the red can", "fact":"It mostly doesn't bottle its own drinks — a network of independent bottlers does that."},
 "SMCI":  {"where":"hidden", "emoji":"🖥️🔩⚡", "what":"Super Micro builds the server racks that AI chips get bolted into — the pickaxe seller of the AI boom.", "hint":"the servers AI chips get bolted into", "fact":"Its founder is still the CEO, more than thirty years after starting it."},
 "AVGO":  {"where":"hidden", "emoji":"📶🔌📱", "what":"Broadcom's chips and software are in everything from iPhones to Wi-Fi routers to AI data centers.", "hint":"chips hiding in your phone, your Wi-Fi and the cloud", "fact":"The company that bought it liked the name so much it gave up its own."},
 "CVNA":  {"where":"store", "emoji":"🚗🪟🎰", "what":"Carvana sells used cars online — famous for its glass car vending-machine towers.", "hint":"the glass car vending machines", "fact":"It was spun out of its founder's father's used-car empire."},
 "NVDA":  {"where":"home", "emoji":"🎮🤖💚", "what":"Nvidia designs the AI chips every tech giant is fighting over — the most valuable company boom of the AI era.", "hint":"the AI chip everyone on earth is fighting over", "fact":"For its first twenty-five years, its customers were mostly video gamers."},
 "GOOGL": {"where":"home", "emoji":"🔍📱🎥", "what":"Alphabet is Google — search, YouTube, Android, Chrome and the Gemini AI models.", "hint":"the search bar you use a hundred times a day", "fact":"It renamed its parent company in 2015 and nobody has used the new name since."},
 "META":  {"where":"home", "emoji":"👍📘🕶️", "what":"Meta owns Facebook, Instagram, WhatsApp and the Quest headsets, and pours enormous sums into AI.", "hint":"the company behind Instagram and WhatsApp", "fact":'It gives every one of its products away for free and sells the attention instead; almost all the revenue comes from that single source.'},
 "ORCL":  {"where":"hidden", "emoji":"🗄️☁️🏢", "what":"Oracle sells the databases and cloud servers that big companies run their operations on.", "hint":"the database company that quietly runs corporate America", "fact":'It spent decades selling databases and is now spending enormous sums to become a cloud landlord.'},
 "RBLX":  {"where":"home", "emoji":"🟥🎮🧱", "what":"Roblox is the online platform where millions of kids build and play each other’s games.", "hint":"the game platform every 10-year-old is on", "fact":'It pays out a share of its revenue to the users who build the things people play.'},
 "HIMS":  {"where":"home", "emoji":"💊📦🪞", "what":"Hims & Hers sells prescription treatments online — hair, skin and weight — shipped to your door.", "hint":"the telehealth app advertising hair-loss pills", "fact":'It sells to patients directly on subscription, routing around the traditional clinic entirely.'},
 "RIOT":  {"where":"hidden", "emoji":"⛏️🟠🔌", "what":"Riot Platforms runs warehouses full of computers that mine Bitcoin.", "hint":"the warehouse full of Bitcoin miners", "fact":'Electricity is its dominant cost, so it puts its operations wherever power is cheapest.'},
 "QCOM":  {"where":"hidden", "emoji":"📡📱🔋", "what":"Qualcomm designs the chips and modems that connect nearly every Android phone to the network.", "hint":"the chip that keeps your phone on the network", "fact":'It collects a royalty on a huge share of the phones sold worldwide, including handsets that contain none of its own chips.'},
 "LLY":   {"where":"home", "emoji":"💊🧬🏥", "what":"Eli Lilly makes the blockbuster weight-loss and diabetes drugs, plus cancer and Alzheimer’s treatments.", "hint":"the drugmaker behind the weight-loss shots", "fact":'Founded in the 1870s, its recent growth comes from a drug class that barely existed ten years ago.'},
 "JPM":   {"where":"store", "emoji":"🏦💳🗽", "what":"JPMorgan Chase is the biggest bank in America — Chase branches, credit cards and Wall Street trading.", "hint":"the biggest bank in America", "fact":'It is designated systemically important, which forces it to hold more capital than smaller banks.'},
 "UBER":  {"where":"home", "emoji":"🚕📱🍔", "what":"Uber is the ride-hailing app — and Uber Eats, which delivers the food.", "hint":"the app you use when you don’t want to drive", "fact":'It classifies the people doing the work as contractors, not employees — a distinction it litigates somewhere in the world almost constantly.'},
 # --- batch 2 of the queue expansion, added 2026-08-19 ------------------------------------
 # Deliberately weighted to consumer, staples, health and financials. The first 40 were 53%
 # Tech + Semis + Crypto, which is repetitive for regulars, leaks information to anyone who
 # notices the bias, and caps the game at a finance-native audience. These are household
 # brands a casual player can actually name.
 "AMZN":  {"where":"home", "emoji":"📦🛒☁️", "what":"Amazon is the everything store — and AWS, the cloud business that quietly earns most of the profit.", "hint":"the boxes on your doorstep", "fact":"Its retail arm is the famous half; a cloud-computing division most shoppers have never heard of makes most of the money."},
 "MCD":   {"where":"store", "emoji":"🍟🍔🤡", "what":"McDonald's is the world's biggest fast-food chain, with more than 40,000 restaurants.", "hint":"the golden arches", "fact":"It makes more of its money as a landlord and franchiser than by selling food directly."},
 "HD":    {"where":"store", "emoji":"🔨🪜🧡", "what":"Home Depot is the big orange home-improvement warehouse — tools, lumber and contractors' supplies.", "hint":"the orange warehouse you visit when something breaks", "fact":"Professional contractors are a minority of its customers but a huge share of its sales."},
 "ABNB":  {"where":"home", "emoji":"🏠🗝️🧳", "what":"Airbnb lets people rent out their homes to travellers, and takes a cut of every booking.", "hint":"how you book a place to stay that isn’t a hotel", "fact":"It owns almost no property — its entire inventory belongs to other people."},
 "CMG":   {"where":"store", "emoji":"🌯🥑🍚", "what":"Chipotle is the fast-casual burrito chain that made the assembly line a selling point.", "hint":"the burrito line where you point at what you want", "fact":"It franchises nothing — every single location is company-owned."},
 "DASH":  {"where":"home", "emoji":"🛵🍜📱", "what":"DoorDash is the app that brings restaurant food to your door, taking a cut from the restaurant and a fee from you.", "hint":"the app that brings dinner from a restaurant you didn’t drive to", "fact":"It took years of losses to reach profit, and its biggest costs walk on two legs."},
 "COST":  {"where":"store", "emoji":"🛒📦🥩", "what":"Costco is the warehouse club that sells in bulk — you pay an annual fee just to shop there.", "hint":"the warehouse where you buy 48 rolls at a time", "fact":"Its membership fees, not its groceries, are where most of the profit comes from."},
 "WMT":   {"where":"store", "emoji":"🛒💙🏪", "what":"Walmart is the largest retailer on earth and America's biggest private employer.", "hint":"the everyday-low-prices superstore", "fact":"It employs more people than any other private company in the United States."},
 "PEP":   {"where":"home", "emoji":"🥤🥔🌽", "what":"PepsiCo sells the drink you're thinking of — plus Doritos, Lay's, Quaker and Gatorade.", "hint":"the cola that isn’t the other one", "fact":"Its snack business is bigger than its drinks business."},
 "TGT":   {"where":"store", "emoji":"🎯🛍️🐶", "what":"Target is the big-box retailer that competes on style rather than only on price.", "hint":"the big-box store with the bullseye", "fact":"It leans on its own in-house labels far more than most of its rivals do."},
 "HSY":   {"where":"home", "emoji":"🍫🥜🎃", "what":"Hershey is the American chocolate maker — Reese's, Kit Kat in the US, and the bars themselves.", "hint":"the chocolate bar in every checkout aisle", "fact":"A charitable trust controls the voting power, so it cannot easily be taken over."},
 "V":     {"where":"hidden", "emoji":"💳🌐🔒", "what":"Visa runs the network that moves card payments between your bank and the shop's bank. It doesn't lend you anything.", "hint":"the network your card runs on", "fact":"It issues no cards and lends no money — banks do both, and it charges a toll on the traffic."},
 "PYPL":  {"where":"home", "emoji":"💸🔵🛒", "what":"PayPal moves money online — checkout buttons, Venmo, and payments between people.", "hint":"the checkout button that isn’t your card", "fact":"It was spun out of an auction site that had bought it years earlier."},
 "GS":    {"where":"hidden", "emoji":"🏦📈🤝", "what":"Goldman Sachs is the Wall Street investment bank — trading, dealmaking and managing money for the very wealthy.", "hint":"the Wall Street bank you’ve heard of but never used", "fact":"It tried and largely abandoned a push into ordinary consumer banking."},
 "PFE":   {"where":"home", "emoji":"💊🧪🔵", "what":"Pfizer is one of the world's biggest drugmakers, best known lately for its COVID vaccine.", "hint":"the drugmaker behind a very famous 2021 shot", "fact":"Its problem is a cliff: several of its biggest sellers lose patent protection this decade."},
 "CVS":   {"where":"store", "emoji":"💊🏪🩺", "what":"CVS is the pharmacy chain that also owns a giant health insurer and the middleman that prices drugs.", "hint":"the corner pharmacy with the long receipts", "fact":"The shop you can walk into is the smallest of its three businesses."},
 "NVO":   {"where":"home", "emoji":"💉🇩🇰⚖️", "what":"Novo Nordisk is the Danish drugmaker behind Ozempic and Wegovy, and a century of insulin before that.", "hint":"the European maker of the weight-loss injection everyone discussed", "fact":"A foundation holds voting control, and it is one of the largest companies in its country by far."},
 "DAL":   {"where":"home", "emoji":"✈️🛫🔴", "what":"Delta is one of the big three US airlines, flying hundreds of thousands of people a day.", "hint":"one of the big three US airlines", "fact":"Its frequent-flyer programme and a credit-card deal earn it billions before a single seat is sold."},
 "UPS":   {"where":"home", "emoji":"📦🚚🟤", "what":"UPS delivers parcels — the brown trucks and the global air freight network behind them.", "hint":"the brown truck", "fact":"Its drivers are unionised, which makes labour talks a market event every few years."},
 "SPOT":  {"where":"home", "emoji":"🎧🟢▶️", "what":"Spotify is the music streaming service — free with ads, or paid without them.", "hint":"the green app your playlists live in", "fact":"Most of its revenue goes straight back out to rights holders, which caps how profitable it can be."},
}
