# Company cards for the 30-answer queue. Two fields per ticker:
#   what  — reveal card: plain-English "what they actually do" (no numbers, no jargon)
#   hint  — hint-ladder "you might know them from" (spoiler-free: never names the company)
CO = {
 "MU":   {"what":"Micron makes memory chips — the storage and RAM inside phones, laptops and the data centers that run AI.",
          "hint":"the memory chips inside your phone and AI data centers"},
 "GME":  {"what":"GameStop is the mall video-game retailer that became the most famous meme stock on earth in 2021.",
          "hint":"the mall video-game store that broke Wall Street in 2021"},
 "CRCL": {"what":"Circle issues USDC — a 'digital dollar' stablecoin used to move money around the crypto world.",
          "hint":"the company behind the USDC digital dollar"},
 "CAT":  {"what":"Caterpillar builds the yellow bulldozers, excavators and mining trucks you see on every construction site.",
          "hint":"the yellow bulldozers on every construction site"},
 "MSTR": {"what":"Strategy (born MicroStrategy) is a software company that turned itself into a giant leveraged Bitcoin vault.",
          "hint":"the software company that turned itself into a Bitcoin vault"},
 "AAPL": {"what":"Apple makes the iPhone, Mac and Apple Watch — and takes a cut of everything in the App Store.",
          "hint":"the phone that's probably in your hand right now"},
 "SNDK": {"what":"SanDisk makes flash memory — the storage in memory cards, USB drives and SSDs.",
          "hint":"the memory cards in your camera and the USB stick in your drawer"},
 "NKE":  {"what":"Nike is the world's biggest sneaker and sportswear brand — the swoosh, Air Jordans, 'Just Do It.'",
          "hint":"the swoosh on half the sneakers you own"},
 "PLTR": {"what":"Palantir sells secretive data-analysis software used by governments, militaries and big companies.",
          "hint":"the secretive data software used by governments and militaries"},
 "INTC": {"what":"Intel is the classic PC chip maker — the processor 'inside' decades of computers, now fighting its way back.",
          "hint":"the classic 'inside your PC' chip maker"},
 "DIS":  {"what":"Disney owns Mickey Mouse, Marvel, Star Wars, Pixar, ESPN and the theme parks.",
          "hint":"Mickey Mouse, Marvel and the theme parks"},
 "COIN": {"what":"Coinbase is the biggest US crypto exchange — the app most Americans use to buy Bitcoin.",
          "hint":"the app most Americans use to buy Bitcoin"},
 "MSFT": {"what":"Microsoft makes Windows, Office, Xbox and the Azure cloud — and is a major backer of OpenAI.",
          "hint":"Windows, Office and Xbox"},
 "AMD":  {"what":"AMD designs the chips inside gaming PCs, consoles and servers — Nvidia's arch-rival in AI chips.",
          "hint":"gaming PC chips — the arch-rival of the AI chip king"},
 "NFLX": {"what":"Netflix is the world's biggest streaming service — the one that invented binge-watching.",
          "hint":"the streaming app you fall asleep to"},
 "HOOD": {"what":"Robinhood is the commission-free trading app that brought a generation of first-timers into the stock market.",
          "hint":"the free stock-trading app with the feather logo"},
 "LULU": {"what":"Lululemon sells premium yoga pants and athleisure — the brand that made leggings a status symbol.",
          "hint":"the yoga pants"},
 "DELL": {"what":"Dell builds PCs, laptops and the servers that data centers — including AI ones — run on.",
          "hint":"the computer brand from the old 'Dude, you're getting a…' ads"},
 "BA":   {"what":"Boeing builds the 737 and 787 — half the planes you've ever flown on.",
          "hint":"maker of half the planes you've flown on"},
 "TSLA": {"what":"Tesla makes electric cars, the Cybertruck, home batteries — and bets big on robots and self-driving.",
          "hint":"the electric car with the most famous CEO on earth"},
 "GEMI": {"what":"Gemini is the crypto exchange founded by the Winklevoss twins of Facebook-lawsuit fame.",
          "hint":"the Winklevoss twins' crypto exchange"},
 "SBUX": {"what":"Starbucks is the world's biggest coffee chain — the green mermaid on every corner.",
          "hint":"the green mermaid on your coffee cup"},
 "MRVL": {"what":"Marvell designs the networking chips that move data around clouds and AI data centers.",
          "hint":"chips that shuttle data around AI data centers"},
 "IBM":  {"what":"IBM — 'Big Blue' — is the original computer giant, now selling cloud, consulting and mainframes.",
          "hint":"'Big Blue' — the original computer giant"},
 "RIVN": {"what":"Rivian makes electric pickups and SUVs — and the vans that deliver your Amazon packages.",
          "hint":"the electric vans that deliver your Amazon packages"},
 "KO":   {"what":"Coca-Cola sells the world's most famous drink — plus Sprite, Fanta, Smartwater and hundreds more.",
          "hint":"the red can"},
 "SMCI": {"what":"Super Micro builds the server racks that AI chips get bolted into — the pickaxe seller of the AI boom.",
          "hint":"the servers AI chips get bolted into"},
 "AVGO": {"what":"Broadcom's chips and software are in everything from iPhones to Wi-Fi routers to AI data centers.",
          "hint":"chips hiding in your phone, your Wi-Fi and the cloud"},
 "CVNA": {"what":"Carvana sells used cars online — famous for its glass car vending-machine towers.",
          "hint":"the glass car vending machines"},
 "NVDA": {"what":"Nvidia designs the AI chips every tech giant is fighting over — the most valuable company boom of the AI era.",
          "hint":"the AI chip everyone on earth is fighting over"},
}
