# Squiggle game universe: ~80 most-talked-about tickers on X.
# Fields: ticker -> (company name, sector, cap bucket)
# Cap buckets (approx, mid-2026): MEGA >$200B, LARGE $20-200B, MID $2-20B, SMALL <$2B
# NOTE: buckets are coarse by design (game hint granularity); the 7 puzzle answers get web-verified.

UNIVERSE = {
    # Mega tech / market cores
    "NVDA": ("NVIDIA", "Semis", "MEGA"),
    "MSFT": ("Microsoft", "Tech", "MEGA"),
    "AAPL": ("Apple", "Tech", "MEGA"),
    "GOOGL": ("Alphabet", "Internet", "MEGA"),
    "AMZN": ("Amazon", "Internet", "MEGA"),
    "META": ("Meta Platforms", "Internet", "MEGA"),
    "TSLA": ("Tesla", "Auto/EV", "MEGA"),
    "AVGO": ("Broadcom", "Semis", "MEGA"),
    "ORCL": ("Oracle", "Tech", "MEGA"),
    "NFLX": ("Netflix", "Media", "MEGA"),
    "LLY": ("Eli Lilly", "Healthcare", "MEGA"),
    "JPM": ("JPMorgan", "Financials", "MEGA"),
    "V": ("Visa", "Financials", "MEGA"),
    "WMT": ("Walmart", "Consumer", "MEGA"),
    "COST": ("Costco", "Consumer", "MEGA"),
    "XOM": ("Exxon Mobil", "Energy", "MEGA"),
    "PLTR": ("Palantir", "Tech", "MEGA"),
    # Large
    "AMD": ("AMD", "Semis", "LARGE"),
    "MU": ("Micron", "Semis", "LARGE"),
    "QCOM": ("Qualcomm", "Semis", "LARGE"),
    "TXN": ("Texas Instruments", "Semis", "LARGE"),
    "ARM": ("Arm Holdings", "Semis", "LARGE"),
    "MRVL": ("Marvell", "Semis", "LARGE"),
    "ANET": ("Arista Networks", "Tech", "LARGE"),
    "INTC": ("Intel", "Semis", "LARGE"),
    "IBM": ("IBM", "Tech", "LARGE"),
    "CRM": ("Salesforce", "Tech", "LARGE"),
    "NOW": ("ServiceNow", "Tech", "LARGE"),
    "SNOW": ("Snowflake", "Tech", "LARGE"),
    "SHOP": ("Shopify", "Internet", "LARGE"),
    "SPOT": ("Spotify", "Media", "LARGE"),
    "UBER": ("Uber", "Internet", "LARGE"),
    "ABNB": ("Airbnb", "Internet", "LARGE"),
    "COIN": ("Coinbase", "Crypto/Fintech", "LARGE"),
    "HOOD": ("Robinhood", "Crypto/Fintech", "LARGE"),
    "MSTR": ("Strategy (MicroStrategy)", "Crypto/Fintech", "LARGE"),
    "PYPL": ("PayPal", "Crypto/Fintech", "LARGE"),
    "SOFI": ("SoFi", "Crypto/Fintech", "LARGE"),
    "GS": ("Goldman Sachs", "Financials", "LARGE"),
    "BA": ("Boeing", "Industrials", "LARGE"),
    "CAT": ("Caterpillar", "Industrials", "LARGE"),
    "GE": ("GE Aerospace", "Industrials", "LARGE"),
    "LMT": ("Lockheed Martin", "Industrials", "LARGE"),
    "RTX": ("RTX", "Industrials", "LARGE"),
    "DE": ("Deere", "Industrials", "LARGE"),
    "DIS": ("Disney", "Media", "LARGE"),
    "KO": ("Coca-Cola", "Consumer", "LARGE"),
    "PEP": ("PepsiCo", "Consumer", "LARGE"),
    "MCD": ("McDonald's", "Consumer", "LARGE"),
    "NKE": ("Nike", "Consumer", "LARGE"),
    "SBUX": ("Starbucks", "Consumer", "LARGE"),
    "LULU": ("Lululemon", "Consumer", "LARGE"),
    "TGT": ("Target", "Consumer", "LARGE"),
    "UNH": ("UnitedHealth", "Healthcare", "LARGE"),
    "PFE": ("Pfizer", "Healthcare", "LARGE"),
    "MRNA": ("Moderna", "Healthcare", "MID"),
    "HIMS": ("Hims & Hers", "Healthcare", "MID"),
    "NVO": ("Novo Nordisk", "Healthcare", "LARGE"),
    "CVX": ("Chevron", "Energy", "LARGE"),
    "OXY": ("Occidental", "Energy", "LARGE"),
    "SPCX": ("SpaceX", "Space", "MEGA"),
    "RKLB": ("Rocket Lab", "Space", "LARGE"),
    "DELL": ("Dell", "Tech", "LARGE"),
    "SMCI": ("Super Micro", "Tech", "LARGE"),
    "NET": ("Cloudflare", "Tech", "LARGE"),
    "CRWD": ("CrowdStrike", "Tech", "LARGE"),
    "RBLX": ("Roblox", "Media", "LARGE"),
    "DKNG": ("DraftKings", "Media", "LARGE"),
    "CVNA": ("Carvana", "Consumer", "LARGE"),
    # Mid / retail cult
    "GME": ("GameStop", "Consumer", "MID"),
    "AMC": ("AMC Entertainment", "Media", "SMALL"),
    "RIVN": ("Rivian", "Auto/EV", "MID"),
    "LCID": ("Lucid", "Auto/EV", "MID"),
    "IONQ": ("IonQ", "Tech", "MID"),
    "RGTI": ("Rigetti", "Tech", "MID"),
    "ACHR": ("Archer Aviation", "Space", "MID"),
    "JOBY": ("Joby Aviation", "Space", "MID"),
    "OKLO": ("Oklo", "Energy", "MID"),
    "CRCL": ("Circle", "Crypto/Fintech", "LARGE"),
    "GEMI": ("Gemini", "Crypto/Fintech", "MID"),
    "SNDK": ("SanDisk", "Semis", "MID"),
    "OUST": ("Ouster", "Tech", "MID"),
    "UPST": ("Upstart", "Crypto/Fintech", "MID"),
    "AFRM": ("Affirm", "Crypto/Fintech", "MID"),
    "CHWY": ("Chewy", "Consumer", "MID"),
    "WEN": ("Wendy's", "Consumer", "MID"),
}
